# =====================================================================
#  AI JOB PORTAL - ENTIRE PROJECT IN ONE FILE
#  Full-Stack Job Portal with AI-Based Resume Screening and Candidate Matching
#
#  HOW TO USE (Google Colab):
#    1. Open https://colab.research.google.com -> New notebook
#    2. Paste this WHOLE file into ONE cell and press Shift + Enter
#    3. It creates every project file, installs libraries and runs the tests.
#       You should see "17 passed" at the end.
#
#  On your own computer: save as all_in_one.py and run  python all_in_one.py
# =====================================================================

import os, subprocess, sys

PROJECT = "job_portal"
FILES = {}

# ---------------------------------------------------------------------
# FILE: .gitignore
# ---------------------------------------------------------------------
FILES['.gitignore'] = '''__pycache__/
*.db
uploads/*
!uploads/.gitkeep
eval/results.json
eval/charts/
.venv/
'''

# ---------------------------------------------------------------------
# FILE: README.md
# ---------------------------------------------------------------------
FILES['README.md'] = r'''# AI Job Portal — Python / Flask implementation

This is the implementation described in the project report **"Full-Stack Job Portal with AI-Based
Resume Screening and Candidate Matching"** (Samrudhi Vishal Dubal, MBA, SRM IST — mentor Ms. Anjana,
Qollabb). It follows the report's architecture (Fig. 3.1), database design (Table 3.3), screening
model (Section 3.7) and evaluation (Chapter IV).

## Features

- **Recruiters**: register, post jobs, view candidates ranked by AI match score with matched and
  missing skills, filter to scores ≥ 60, update application status, download resumes.
- **Job seekers**: register, search jobs, apply with a PDF / DOCX / TXT resume (max 5 MB), see their own
  match score, missing skills and application status.
- **Security**: Werkzeug password hashing, session-based login, role checks, file-type and size
  validation, recruiters can only see candidates for their own jobs.
- **AI screening engine** (`screening/`): resume parsing, a synonym-aware skill taxonomy, TF-IDF
  cosine similarity and a weighted, explainable 0–100 score.

## Project structure

```
job_portal/
  app.py                    Flask web application (routes, auth, SQLite)
  screening/
    parser.py               text extraction (pypdf, python-docx) + email, phone, experience, education, skills
    skills.py               skill taxonomy: ~50 canonical skills with synonyms (k8s -> kubernetes, ...)
    matcher.py              hybrid model + baseline methods (keyword, TF-IDF only, skill only)
  templates/                Jinja2 HTML pages
  static/style.css
  eval/
    generate_dataset.py     builds the labelled test set (150 resumes x 6 jobs, fixed seed)
    evaluate.py             reproduces Tables 4.2 - 4.9 (P@10, R@20, NDCG@10, Spearman, thresholds, ...)
  tests/                    functional tests from Table 4.1 + engine unit tests (pytest)
  seed_demo.py              loads a demo recruiter, six jobs and eight applicants
```

## How to run

```bash
cd job_portal
python -m venv .venv
source .venv/bin/activate          # Windows: .venv\Scripts\activate
pip install -r requirements.txt

python -m eval.generate_dataset    # creates eval/data/*.json
python seed_demo.py                # optional demo data
python app.py                      # open http://127.0.0.1:5000
```

Demo logins (after `seed_demo.py`): recruiter `hr@demo.com` / `demo123`; job seekers
`c0@demo.com` … `c7@demo.com` / `demo123`.

Set `SECRET_KEY` as an environment variable before deploying anywhere public.

## The match score (Section 3.7)

```
Match Score = 100 × (0.35 × Text + 0.40 × Skills + 0.15 × Experience + 0.10 × Education)
```

| Component  | How it is computed |
|------------|--------------------|
| Text       | TF-IDF (unigrams + bigrams, English stop words) cosine similarity between JD and resume, divided by 0.5 and capped at 1 |
| Skills     | required skills found in the resume (via synonyms) ÷ required skills in the JD |
| Experience | largest "N years" in the resume ÷ JD minimum experience, capped at 1 |
| Education  | resume level ÷ required level (diploma 1, bachelor 2, master/MBA 3, doctorate 4), capped at 1 |

The default shortlisting threshold is **60** (Table 4.6).

## Tests and evaluation

```bash
python -m pytest -q                # 17 tests (11 functional cases from Table 4.1 + engine tests)
python -m eval.evaluate --charts   # prints Tables 4.2-4.9, saves eval/results.json and eval/charts/*.png
```

Because the test dataset is regenerated by `generate_dataset.py`, the exact figures can differ
slightly from those printed in the report; the overall pattern (hybrid model best at the top of the
ranking, keyword screening most easily fooled by stuffed resumes, threshold 60 catching every strong
fit while cutting ~89% of the screening workload) is reproduced.
'''

# ---------------------------------------------------------------------
# FILE: app.py
# ---------------------------------------------------------------------
FILES['app.py'] = '''"""AI Job Portal - Flask web application (Section 3.5 of the report).

Run:  python app.py        then open http://127.0.0.1:5000
"""

import json
import os
import sqlite3
from functools import wraps
from pathlib import Path

from flask import (Flask, abort, flash, g, redirect, render_template, request,
                   send_from_directory, session, url_for)
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename

from screening import (EDUCATION_NAMES, SHORTLIST_THRESHOLD, extract_text,
                       parse_resume, rank_candidates)

BASE = Path(__file__).resolve().parent
ALLOWED = {".pdf", ".docx", ".txt"}
STATUSES = ["Applied", "Shortlisted", "Interview", "Rejected", "Hired"]

app = Flask(__name__)
app.config.update(
    SECRET_KEY=os.environ.get("SECRET_KEY", "dev-secret-change-me"),
    DATABASE=os.environ.get("DATABASE", str(BASE / "portal.db")),
    UPLOAD_FOLDER=os.environ.get("UPLOAD_FOLDER", str(BASE / "uploads")),
    MAX_CONTENT_LENGTH=5 * 1024 * 1024,  # 5 MB resume limit
)

SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('seeker', 'recruiter')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS jobs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    recruiter_id INTEGER NOT NULL REFERENCES users(id),
    title TEXT NOT NULL,
    location TEXT,
    description TEXT NOT NULL,
    min_experience REAL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS applications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER NOT NULL REFERENCES jobs(id),
    seeker_id INTEGER NOT NULL REFERENCES users(id),
    resume_path TEXT NOT NULL,
    score REAL,
    breakdown TEXT,
    status TEXT DEFAULT 'Applied',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (job_id, seeker_id)
);
"""


# ---------------------------------------------------------------- database

def db():
    if "db" not in g:
        g.db = sqlite3.connect(app.config["DATABASE"])
        g.db.row_factory = sqlite3.Row
    return g.db


@app.teardown_appcontext
def close_db(_exc):
    conn = g.pop("db", None)
    if conn is not None:
        conn.close()


def init_db():
    with app.app_context():
        db().executescript(SCHEMA)
        db().commit()


# ---------------------------------------------------------------- auth helpers

def login_required(role=None):
    def decorator(view):
        @wraps(view)
        def wrapped(*args, **kwargs):
            if "user_id" not in session:
                flash("Please log in to continue.")
                return redirect(url_for("login", next=request.path))
            if role and session.get("role") != role:
                flash("Access denied for your account type.")
                return redirect(url_for("login"))
            return view(*args, **kwargs)
        return wrapped
    return decorator


@app.context_processor
def inject_user():
    return {"current_role": session.get("role"), "current_name": session.get("name"),
            "threshold": SHORTLIST_THRESHOLD}


@app.template_filter("fromjson")
def fromjson(value):
    return json.loads(value) if value else {}


# ---------------------------------------------------------------- public pages

@app.route("/")
def index():
    q = request.args.get("q", "").strip()
    sql = "SELECT j.*, u.name AS company FROM jobs j JOIN users u ON u.id = j.recruiter_id"
    params = ()
    if q:
        sql += " WHERE j.title LIKE ? OR j.description LIKE ? OR j.location LIKE ?"
        params = (f"%{q}%",) * 3
    jobs = db().execute(sql + " ORDER BY j.created_at DESC, j.id DESC", params).fetchall()
    return render_template("index.html", jobs=jobs, q=q)


@app.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        name = request.form.get("name", "").strip()
        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")
        role = request.form.get("role", "seeker")
        if not name or not email or len(password) < 6 or role not in ("seeker", "recruiter"):
            flash("Please fill all fields. Password must be at least 6 characters.")
            return render_template("register.html"), 400
        try:
            db().execute("INSERT INTO users (name, email, password, role) VALUES (?, ?, ?, ?)",
                         (name, email, generate_password_hash(password), role))
            db().commit()
        except sqlite3.IntegrityError:
            flash("Email already registered")
            return render_template("register.html"), 400
        flash("Registration successful. Please log in.")
        return redirect(url_for("login"))
    return render_template("register.html")


@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email", "").strip().lower()
        user = db().execute("SELECT * FROM users WHERE email = ?", (email,)).fetchone()
        if not user or not check_password_hash(user["password"], request.form.get("password", "")):
            flash("Invalid credentials")
            return render_template("login.html"), 401
        session.clear()
        session.update(user_id=user["id"], role=user["role"], name=user["name"])
        nxt = request.args.get("next", "")
        return redirect(nxt if nxt.startswith("/") and not nxt.startswith("//") else url_for("dashboard"))
    return render_template("login.html")


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("index"))


@app.route("/jobs/<int:job_id>")
def job_detail(job_id):
    job = get_job_or_404(job_id)
    applied = None
    if session.get("role") == "seeker":
        applied = db().execute("SELECT * FROM applications WHERE job_id = ? AND seeker_id = ?",
                               (job_id, session["user_id"])).fetchone()
    return render_template("job_detail.html", job=job, applied=applied)


def get_job_or_404(job_id):
    job = db().execute("SELECT j.*, u.name AS company FROM jobs j JOIN users u "
                       "ON u.id = j.recruiter_id WHERE j.id = ?", (job_id,)).fetchone()
    if job is None:
        abort(404)
    return job


# ---------------------------------------------------------------- dashboards

@app.route("/dashboard")
@login_required()
def dashboard():
    if session["role"] == "recruiter":
        jobs = db().execute(
            "SELECT j.*, COUNT(a.id) AS applicants, "
            "SUM(CASE WHEN a.score >= ? THEN 1 ELSE 0 END) AS above_threshold "
            "FROM jobs j LEFT JOIN applications a ON a.job_id = j.id "
            "WHERE j.recruiter_id = ? GROUP BY j.id ORDER BY j.created_at DESC, j.id DESC",
            (SHORTLIST_THRESHOLD, session["user_id"])).fetchall()
        return render_template("recruiter_dashboard.html", jobs=jobs)
    apps = db().execute(
        "SELECT a.*, j.title, j.location FROM applications a JOIN jobs j ON j.id = a.job_id "
        "WHERE a.seeker_id = ? ORDER BY a.created_at DESC", (session["user_id"],)).fetchall()
    return render_template("seeker_dashboard.html", apps=apps)


# ---------------------------------------------------------------- recruiter

@app.route("/jobs/new", methods=["GET", "POST"])
@login_required("recruiter")
def new_job():
    if request.method == "POST":
        title = request.form.get("title", "").strip()
        description = request.form.get("description", "").strip()
        location = request.form.get("location", "").strip()
        try:
            min_exp = float(request.form.get("min_experience") or 0)
        except ValueError:
            min_exp = -1
        if not title or not description or min_exp < 0:
            flash("Title, description and a valid minimum experience are required.")
            return render_template("job_form.html"), 400
        db().execute("INSERT INTO jobs (recruiter_id, title, location, description, min_experience) "
                     "VALUES (?, ?, ?, ?, ?)",
                     (session["user_id"], title, location, description, min_exp))
        db().commit()
        flash("Job posted.")
        return redirect(url_for("dashboard"))
    return render_template("job_form.html")


@app.route("/jobs/<int:job_id>/candidates")
@login_required("recruiter")
def candidates(job_id):
    job = get_job_or_404(job_id)
    if job["recruiter_id"] != session["user_id"]:
        abort(403)
    rows = db().execute(
        "SELECT a.*, u.name, u.email FROM applications a JOIN users u ON u.id = a.seeker_id "
        "WHERE a.job_id = ? ORDER BY a.score DESC", (job_id,)).fetchall()
    only_shortlist = request.args.get("filter") == "shortlist"
    if only_shortlist:
        rows = [r for r in rows if r["score"] >= SHORTLIST_THRESHOLD]
    return render_template("candidates.html", job=job, rows=rows, statuses=STATUSES,
                           only_shortlist=only_shortlist, education_names=EDUCATION_NAMES)


@app.route("/applications/<int:app_id>/status", methods=["POST"])
@login_required("recruiter")
def update_status(app_id):
    row = db().execute("SELECT a.job_id, j.recruiter_id FROM applications a JOIN jobs j "
                       "ON j.id = a.job_id WHERE a.id = ?", (app_id,)).fetchone()
    if row is None:
        abort(404)
    if row["recruiter_id"] != session["user_id"]:
        abort(403)
    status = request.form.get("status")
    if status not in STATUSES:
        abort(400)
    db().execute("UPDATE applications SET status = ? WHERE id = ?", (status, app_id))
    db().commit()
    flash("Status updated.")
    return redirect(url_for("candidates", job_id=row["job_id"]))


@app.route("/applications/<int:app_id>/resume")
@login_required()
def view_resume(app_id):
    row = db().execute("SELECT a.*, j.recruiter_id FROM applications a JOIN jobs j "
                       "ON j.id = a.job_id WHERE a.id = ?", (app_id,)).fetchone()
    if row is None:
        abort(404)
    if session["user_id"] not in (row["recruiter_id"], row["seeker_id"]):
        abort(403)
    return send_from_directory(app.config["UPLOAD_FOLDER"], row["resume_path"], as_attachment=True)


# ---------------------------------------------------------------- job seeker

@app.route("/jobs/<int:job_id>/apply", methods=["GET", "POST"])
@login_required("seeker")
def apply(job_id):
    job = get_job_or_404(job_id)
    if request.method == "POST":
        file = request.files.get("resume")
        ext = Path(file.filename).suffix.lower() if file and file.filename else ""
        if ext not in ALLOWED:
            flash("Upload a PDF, DOCX or TXT resume.")
            return redirect(request.url)
        filename = secure_filename(f"{session['user_id']}_{job_id}{ext}")
        path = Path(app.config["UPLOAD_FOLDER"]) / filename
        path.parent.mkdir(parents=True, exist_ok=True)
        file.save(path)
        try:
            text = extract_text(path)
        except Exception:
            path.unlink(missing_ok=True)
            flash("Could not read that file. Please upload a text-based PDF, DOCX or TXT resume.")
            return redirect(request.url)
        if not text.strip():
            path.unlink(missing_ok=True)
            flash("No text found in the resume (scanned images are not supported).")
            return redirect(request.url)

        result = rank_candidates(job["description"], {"self": text},
                                 min_experience=job["min_experience"])[0]
        parsed = parse_resume(text)
        breakdown = result.breakdown()
        breakdown.update(experience_years=parsed["experience_years"],
                         education_level=parsed["education_level"],
                         phone=parsed["phone"], parsed_email=parsed["email"])
        db().execute(
            "INSERT INTO applications (job_id, seeker_id, resume_path, score, breakdown) "
            "VALUES (?, ?, ?, ?, ?) ON CONFLICT(job_id, seeker_id) DO UPDATE SET "
            "resume_path = excluded.resume_path, score = excluded.score, "
            "breakdown = excluded.breakdown, status = 'Applied', created_at = CURRENT_TIMESTAMP",
            (job_id, session["user_id"], filename, result.score, json.dumps(breakdown)))
        db().commit()
        flash(f"Application submitted. Your match score is {result.score:.0f}/100.")
        return redirect(url_for("dashboard"))
    return render_template("apply.html", job=job)


@app.errorhandler(413)
def too_large(_e):
    flash("File is larger than 5 MB.")
    return redirect(request.url)


init_db()

if __name__ == "__main__":
    app.run(debug=os.environ.get("FLASK_DEBUG") == "1")
'''

# ---------------------------------------------------------------------
# FILE: eval/__init__.py
# ---------------------------------------------------------------------
FILES['eval/__init__.py'] = ''''''

# ---------------------------------------------------------------------
# FILE: eval/evaluate.py
# ---------------------------------------------------------------------
FILES['eval/evaluate.py'] = r'''"""Evaluate the screening engine on the labelled test dataset (Chapter IV of the report).

Usage (from the job_portal folder):
    python -m eval.generate_dataset
    python -m eval.evaluate            # prints the tables, writes eval/results.json
    python -m eval.evaluate --charts   # also saves PNG charts to eval/charts (needs matplotlib)
"""

import argparse
import json
import math
import time
from pathlib import Path

import numpy as np
from scipy.stats import spearmanr

from screening.matcher import (DEFAULT_WEIGHTS, keyword_scores, rank_candidates,
                               skill_scores, tfidf_scores)
from screening.parser import parse_resume

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"


# ---------------------------------------------------------------- metrics

def ranking(scores):
    return sorted(scores, key=lambda cid: scores[cid], reverse=True)


def precision_at(order, labels, k=10):
    return sum(labels[c] == 2 for c in order[:k]) / k


def recall_at(order, labels, k=20):
    strong = sum(v == 2 for v in labels.values())
    return sum(labels[c] == 2 for c in order[:k]) / strong if strong else 0.0


def ndcg_at(order, labels, k=10):
    dcg = sum((2 ** labels[c] - 1) / math.log2(i + 2) for i, c in enumerate(order[:k]))
    ideal = sorted(labels.values(), reverse=True)[:k]
    idcg = sum((2 ** g - 1) / math.log2(i + 2) for i, g in enumerate(ideal))
    return dcg / idcg if idcg else 0.0


def table(headers, rows):
    widths = [max(len(str(x)) for x in col) for col in zip(headers, *rows)]
    line = lambda r: "| " + " | ".join(str(x).ljust(w) for x, w in zip(r, widths)) + " |"
    return "\n".join([line(headers), "|" + "|".join("-" * (w + 2) for w in widths) + "|"]
                     + [line(r) for r in rows])


# ---------------------------------------------------------------- evaluation

def hybrid_scores(job, texts, weights=None):
    res = rank_candidates(job["description"], texts, weights=weights,
                          min_experience=job["min_experience"], min_education=job["min_education"])
    return {r.candidate_id: r.score for r in res}, res


def main(charts=False):
    jobs = json.loads((DATA / "jobs.json").read_text())
    resumes = json.loads((DATA / "resumes.json").read_text())
    texts = {r["id"]: r["text"] for r in resumes}
    stuffed_for = {j["title"]: {r["id"] for r in resumes if r.get("target") == j["title"]} for j in jobs}
    out = {}

    # 4.2 Parser accuracy
    ok = {"email": 0, "phone": 0, "experience": 0, "education": 0}
    recall, precision = [], []
    for r in resumes:
        p, t = parse_resume(r["text"]), r["truth"]
        ok["email"] += p["email"] == t["email"]
        ok["phone"] += p["phone"] == t["phone"]
        ok["experience"] += abs(p["experience_years"] - t["experience_years"]) < 1e-6
        ok["education"] += p["education_level"] == t["education_level"]
        truth = set(t["skills"])
        found = set(p["skills"])
        # stuffed resumes contain extra keywords by design, so judge skills on the genuine part only
        if r["kind"] == "stuffed":
            found = set(parse_resume(r["text"].split("\n\nKeywords:")[0])["skills"])
        recall.append(len(truth & found) / len(truth))
        precision.append(len(truth & found) / len(found) if found else 0)
    n = len(resumes)
    parser_rows = [[k.capitalize(), v, n, f"{100 * v / n:.1f}"] for k, v in ok.items()]
    parser_rows += [["Skills (recall)", "-", n, f"{100 * np.mean(recall):.1f}"],
                    ["Skills (precision)", "-", n, f"{100 * np.mean(precision):.1f}"]]
    print("\nTable 4.2 Resume parser field extraction accuracy\n")
    print(table(["Field", "Correct", "Total", "Accuracy (%)"], parser_rows))
    out["parser"] = parser_rows

    # 4.3 / 4.4 Method comparison
    methods = {"A. Boolean keyword": lambda j: keyword_scores(j["skills"], texts),
               "B. TF-IDF only": lambda j: tfidf_scores(j["description"], texts),
               "C. Skill match only": lambda j: skill_scores(j["skills"], texts),
               "D. Hybrid (proposed)": lambda j: hybrid_scores(j, texts)[0]}
    summary, per_job = [], {m: {} for m in methods}
    for name, fn in methods.items():
        p10, r20, nd, rho, stuffed = [], [], [], [], []
        for j in jobs:
            labels = {r["id"]: r["labels"][j["id"]] for r in resumes}
            s = fn(j)
            order = ranking(s)
            p10.append(precision_at(order, labels))
            r20.append(recall_at(order, labels))
            nd.append(ndcg_at(order, labels))
            ids = list(labels)
            rho.append(spearmanr([s[c] for c in ids], [labels[c] for c in ids]).statistic)
            stuffed.append(len(set(order[:10]) & stuffed_for[j["title"]]))
            per_job[name][j["title"]] = p10[-1]
        summary.append([name, f"{np.mean(p10):.3f}", f"{np.mean(r20):.3f}", f"{np.mean(nd):.3f}",
                        f"{np.mean(rho):.3f}", f"{np.mean(stuffed):.2f}"])
    print("\nTable 4.3 Comparison of screening methods (average of six job descriptions)\n")
    print(table(["Method", "P@10", "R@20", "NDCG@10", "Spearman", "Stuffed in top 10"], summary))
    rows = [[j["title"]] + [f"{per_job[m][j['title']]:.2f}" for m in methods] for j in jobs]
    rows.append(["Average"] + [f"{np.mean(list(per_job[m].values())):.2f}" for m in methods])
    print("\nTable 4.4 Precision at 10 by job description\n")
    print(table(["Job"] + [m.split()[1] if m[1] == "." else m for m in methods], rows))
    out["methods"], out["per_job_p10"] = summary, per_job

    # 4.5 Score distribution by relevance, 4.6 thresholds
    groups = {"Strong fit (label 2)": [], "Partial fit (label 1)": [],
              "Not relevant (label 0)": [], "Keyword-stuffed (label 0)": []}
    pairs = []  # (score, label)
    for j in jobs:
        s, _ = hybrid_scores(j, texts)
        for r in resumes:
            lab = r["labels"][j["id"]]
            pairs.append((s[r["id"]], lab))
            if r["id"] in stuffed_for[j["title"]]:
                groups["Keyword-stuffed (label 0)"].append(s[r["id"]])
            else:
                groups[{2: "Strong fit (label 2)", 1: "Partial fit (label 1)", 0: "Not relevant (label 0)"}[lab]].append(s[r["id"]])
    dist = [[g, len(v), f"{np.mean(v):.2f}", f"{np.std(v, ddof=1):.2f}", f"{min(v):.2f}", f"{max(v):.2f}"]
            for g, v in groups.items() if v]
    print("\nTable 4.5 Hybrid match score by ground-truth relevance\n")
    print(table(["Group", "Count", "Mean", "Std", "Min", "Max"], dist))
    out["distribution"] = dist

    thr_rows = []
    total_strong = sum(l == 2 for _, l in pairs)
    for cut in (40, 50, 60, 70, 80):
        listed = [(s, l) for s, l in pairs if s >= cut]
        tp = sum(l == 2 for _, l in listed)
        fp, fn = len(listed) - tp, total_strong - tp
        prec = tp / len(listed) if listed else 0
        rec = tp / total_strong if total_strong else 0
        f1 = 2 * prec * rec / (prec + rec) if prec + rec else 0
        thr_rows.append([cut, len(listed), tp, fp, fn, f"{prec:.3f}", f"{rec:.3f}", f"{f1:.3f}",
                         f"{100 * (1 - len(listed) / len(pairs)):.1f}"])
    print("\nTable 4.6 Effect of shortlisting threshold\n")
    print(table(["Cut-off", "Listed", "TP", "FP", "FN", "Precision", "Recall", "F1", "Saving %"], thr_rows))
    out["thresholds"] = thr_rows

    # 4.7 Weight sensitivity
    settings = {"Proposed (35, 40, 15, 10)": DEFAULT_WEIGHTS,
                "Text-heavy (70, 20, 5, 5)": dict(text=.70, skills=.20, experience=.05, education=.05),
                "Skill-heavy (15, 70, 10, 5)": dict(text=.15, skills=.70, experience=.10, education=.05),
                "Equal (25, 25, 25, 25)": dict(text=.25, skills=.25, experience=.25, education=.25)}
    sens = []
    for name, w in settings.items():
        p10, nd, rho = [], [], []
        for j in jobs:
            labels = {r["id"]: r["labels"][j["id"]] for r in resumes}
            s, _ = hybrid_scores(j, texts, w)
            order = ranking(s)
            p10.append(precision_at(order, labels))
            nd.append(ndcg_at(order, labels))
            ids = list(labels)
            rho.append(spearmanr([s[c] for c in ids], [labels[c] for c in ids]).statistic)
        sens.append([name, f"{np.mean(p10):.3f}", f"{np.mean(nd):.3f}", f"{np.mean(rho):.3f}"])
    print("\nTable 4.7 Sensitivity to component weights (Text, Skills, Experience, Education)\n")
    print(table(["Weights", "P@10", "NDCG@10", "Spearman"], sens))
    out["weights"] = sens

    # 4.8 Top ten for the first job
    job = jobs[0]
    _, res = hybrid_scores(job, texts)
    by_id = {r["id"]: r for r in resumes}
    top = [[i + 1, m.candidate_id, f"{by_id[m.candidate_id]['family']}, {by_id[m.candidate_id]['kind']}",
            f"{m.score:.2f}", len(m.matched_skills), ", ".join(m.missing_skills) or "None"]
           for i, m in enumerate(res[:10])]
    print(f"\nTable 4.8 Top ten candidates for the {job['title']} job\n")
    print(table(["Rank", "Candidate", "Actual profile", "Score", "Matched", "Missing"], top))
    out["top10"] = top

    # 4.9 Processing time
    times = []
    for j in jobs:
        start = time.perf_counter()
        hybrid_scores(j, texts)
        ms = (time.perf_counter() - start) * 1000 / len(texts)
        times.append([j["title"], f"{ms:.2f}"])
    times.append(["Average", f"{np.mean([float(t[1]) for t in times]):.2f}"])
    print("\nTable 4.9 Processing time per resume (ms)\n")
    print(table(["Job", "ms / resume"], times))
    out["timing"] = times

    (HERE / "results.json").write_text(json.dumps(out, indent=2, default=float))
    print(f"\nSaved results to {HERE / 'results.json'}")
    if charts:
        save_charts(out, groups)


def save_charts(out, groups):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    folder = HERE / "charts"
    folder.mkdir(exist_ok=True)

    names = [r[0] for r in out["methods"]]
    x = np.arange(len(names))
    fig, ax = plt.subplots(figsize=(8, 4.5))
    for k, (col, label) in enumerate([(1, "Precision@10"), (3, "NDCG@10"), (4, "Spearman")]):
        ax.bar(x + (k - 1) * 0.25, [float(r[col]) for r in out["methods"]], 0.25, label=label)
    ax.set_xticks(x, names, fontsize=8)
    ax.set_ylim(0, 1.05)
    ax.set_title("Ranking quality by screening method")
    ax.legend()
    fig.tight_layout()
    fig.savefig(folder / "methods.png", dpi=150)

    fig, ax = plt.subplots(figsize=(8, 4.5))
    ax.boxplot(list(groups.values()), tick_labels=[g.replace(" (", "\n(") for g in groups])
    ax.axhline(60, color="red", linestyle="--", linewidth=1)
    ax.set_ylabel("Hybrid match score")
    ax.set_title("Distribution of hybrid scores by ground-truth relevance")
    fig.tight_layout()
    fig.savefig(folder / "distribution.png", dpi=150)

    cuts = [r[0] for r in out["thresholds"]]
    fig, ax = plt.subplots(figsize=(8, 4.5))
    for col, label in [(5, "Precision"), (6, "Recall"), (7, "F1")]:
        ax.plot(cuts, [float(r[col]) for r in out["thresholds"]], marker="o", label=label)
    ax.set_xlabel("Shortlist threshold")
    ax.set_ylim(0, 1.05)
    ax.legend()
    ax.set_title("Precision, recall and F1 at different thresholds")
    fig.tight_layout()
    fig.savefig(folder / "thresholds.png", dpi=150)
    print(f"Saved charts to {folder}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--charts", action="store_true")
    main(ap.parse_args().charts)
'''

# ---------------------------------------------------------------------
# FILE: eval/generate_dataset.py
# ---------------------------------------------------------------------
FILES['eval/generate_dataset.py'] = r'''"""Generate the controlled, labelled test dataset (Section 3.4 of the report).

Six job families; for each: 10 strong resumes, 12 partial resumes, plus 18
keyword-stuffed resumes overall (each job description targeted by exactly 3).
A fixed random seed makes the dataset reproducible.

Usage:  python -m eval.generate_dataset      (from the job_portal folder)
Writes: eval/data/jobs.json, eval/data/resumes.json
"""

import json
import random
from pathlib import Path

SEED = 42
OUT = Path(__file__).resolve().parent / "data"

FIRST = ["Aarav", "Diya", "Rohan", "Sneha", "Vivaan", "Ananya", "Kabir", "Isha", "Arjun", "Meera",
         "Siddharth", "Priya", "Aditya", "Neha", "Kunal", "Pooja", "Rahul", "Tanvi", "Yash", "Riya"]
LAST = ["Sharma", "Patil", "Iyer", "Nair", "Deshmukh", "Pawar", "Shinde", "Kulkarni", "Joshi",
        "Mehta", "Reddy", "Gupta", "Kapoor", "Rao", "Jain"]

# Each family: required skills (canonical) with alternative ways of writing them,
# responsibilities, minimum experience and minimum education (1 diploma .. 4 PhD).
FAMILIES = {
    "Python Backend Developer": {
        "skills": {"python": ["Python", "Python3"], "django": ["Django", "Django REST Framework"],
                   "flask": ["Flask"], "rest api": ["REST API", "RESTful services"],
                   "sql": ["SQL", "PostgreSQL", "MySQL"], "git": ["Git", "GitHub"],
                   "docker": ["Docker", "containerization"], "aws": ["AWS", "Amazon Web Services"]},
        "duties": ["built and maintained backend services and APIs", "designed database schemas and wrote optimised queries",
                   "wrote unit tests and reviewed code", "deployed microservices to the cloud",
                   "integrated third-party payment and messaging services"],
        "min_exp": 2, "edu": 2, "qual": "B.Tech or equivalent", "location": "Pune (Hybrid)",
    },
    "Data Analyst": {
        "skills": {"sql": ["SQL", "MySQL", "T-SQL"], "excel": ["Excel", "Advanced Excel"],
                   "python": ["Python"], "pandas": ["pandas"], "power bi": ["Power BI", "PowerBI"],
                   "statistics": ["statistics", "statistical analysis"],
                   "data visualization": ["data visualization", "data visualisation"],
                   "tableau": ["Tableau"]},
        "duties": ["prepared weekly business dashboards", "cleaned and analysed sales data",
                   "presented insights to managers", "automated MIS reports",
                   "performed cohort and trend analysis"],
        "min_exp": 1, "edu": 2, "qual": "B.Sc or equivalent", "location": "Remote",
    },
    "DevOps Engineer": {
        "skills": {"aws": ["AWS", "EC2"], "docker": ["Docker"], "kubernetes": ["Kubernetes", "k8s", "EKS"],
                   "ci/cd": ["CI/CD", "Jenkins", "GitHub Actions"], "terraform": ["Terraform", "infrastructure as code"],
                   "linux": ["Linux", "Ubuntu"], "shell scripting": ["shell scripting", "Bash"],
                   "monitoring": ["monitoring", "Prometheus", "Grafana"]},
        "duties": ["managed cloud infrastructure and deployment pipelines", "reduced release time by automating builds",
                   "maintained production clusters with high availability", "handled incident response and on-call",
                   "hardened servers and managed access policies"],
        "min_exp": 3, "edu": 2, "qual": "B.E. or equivalent", "location": "Bengaluru",
    },
    "QA Engineer": {
        "skills": {"selenium": ["Selenium", "Selenium WebDriver"], "manual testing": ["manual testing", "functional testing"],
                   "automation testing": ["automation testing", "test automation"], "jira": ["JIRA", "defect tracking"],
                   "api testing": ["API testing", "Postman"], "sql": ["SQL", "MySQL"],
                   "pytest": ["pytest", "TestNG"], "agile": ["Agile", "Scrum"]},
        "duties": ["wrote and executed test plans for web releases", "logged and tracked defects to closure",
                   "built regression suites for every sprint", "validated backend data with queries",
                   "worked with developers to reproduce production issues"],
        "min_exp": 2, "edu": 2, "qual": "B.Tech or equivalent", "location": "Hyderabad",
    },
    "HR Executive": {
        "skills": {"recruitment": ["recruitment", "Talent Acquisition"], "onboarding": ["onboarding", "induction"],
                   "payroll": ["payroll", "payroll processing"],
                   "employee engagement": ["employee engagement", "employee relations"],
                   "hrms": ["HRMS", "Workday"], "labour law": ["labour law", "statutory compliance"],
                   "performance management": ["performance management", "appraisals"],
                   "excel": ["MS Excel", "Excel"]},
        "duties": ["managed end-to-end hiring for business teams", "coordinated joining formalities for new employees",
                   "maintained employee records and attendance", "organised engagement and wellness activities",
                   "handled employee queries and exit formalities"],
        "min_exp": 2, "edu": 3, "qual": "MBA in HR or equivalent", "location": "Mumbai",
    },
    "Digital Marketing Executive": {
        "skills": {"seo": ["SEO", "search engine optimization"], "sem": ["SEM", "Google Ads"],
                   "social media marketing": ["social media marketing", "Meta Ads"],
                   "content marketing": ["content marketing", "copywriting"],
                   "google analytics": ["Google Analytics", "GA4"], "email marketing": ["email marketing", "Mailchimp"],
                   "excel": ["Excel"], "communication": ["communication skills", "communication"]},
        "duties": ["planned and ran paid campaigns for product launches", "grew organic website traffic",
                   "managed brand pages and posting calendars", "wrote blogs and landing page copy",
                   "reported campaign performance to stakeholders"],
        "min_exp": 1, "edu": 2, "qual": "BBA or any graduate", "location": "Pune",
    },
}

# Closely related families: a strong resume from one is a partial fit for the other (label 1).
RELATED = {("Python Backend Developer", "DevOps Engineer"), ("DevOps Engineer", "Python Backend Developer"),
           ("QA Engineer", "Python Backend Developer")}

EDU_TEXT = {1: "Diploma in {}", 2: "B.Tech in {}", 3: "MBA in {}", 4: "PhD in {}"}
EDU_FIELD = {"Python Backend Developer": "Computer Science", "Data Analyst": "Statistics",
             "DevOps Engineer": "Information Technology", "QA Engineer": "Computer Engineering",
             "HR Executive": "Human Resources", "Digital Marketing Executive": "Marketing"}


def job_description(title, fam):
    skills = ", ".join(fam["skills"])
    duties = "; ".join(fam["duties"])
    return (f"We are hiring a {title}. Minimum {fam['min_exp']} years of experience. "
            f"Required skills: {skills}. Responsibilities: {duties}. Qualification: {fam['qual']}.")


def write_skill(rng, canon, alts):
    """About half of the skills are written with a synonym or alternative term."""
    return rng.choice(alts[1:]) if len(alts) > 1 and rng.random() < 0.5 else alts[0]


def make_resume(rng, rid, family, kind):
    fam = FAMILIES[family]
    canon = list(fam["skills"])
    if kind in ("strong", "stuffed"):  # a stuffed resume is a genuine strong resume of its own family
        n_skills = rng.randint(6, 8)
        years = round(fam["min_exp"] + rng.uniform(0.5, 4.0), 1)
        edu = fam["edu"] if rng.random() < 0.8 else min(fam["edu"] + 1, 4)
    else:  # partial
        n_skills = rng.randint(2, 4)
        years = round(rng.uniform(0.2, max(fam["min_exp"] * 0.6, 0.4)), 1)
        edu = 1 if rng.random() < 0.4 else max(fam["edu"] - 1, 1)
    chosen = rng.sample(canon, n_skills)
    skill_words = [write_skill(rng, c, fam["skills"][c]) for c in chosen]
    duties = rng.sample(fam["duties"], 3)
    name = f"{rng.choice(FIRST)} {rng.choice(LAST)}"
    email = f"{name.split()[0].lower()}.{rid.lower()}@example.com"
    phone = f"9{rng.randint(100000000, 999999999)}"
    text = "\n".join([
        name, f"Email: {email} | Phone: +91 {phone[:5]} {phone[5:]}", "",
        f"Summary: {family} with {years} years of experience.", "",
        "Skills: " + ", ".join(skill_words), "",
        "Experience:", *[f"- {d.capitalize()}." for d in duties], "",
        "Education: " + EDU_TEXT[edu].format(EDU_FIELD[family]),
    ])
    return {"id": rid, "family": family, "kind": kind, "text": text,
            "truth": {"email": email, "phone": phone, "experience_years": years,
                      "education_level": edu, "skills": sorted(chosen)}}


def main():
    rng = random.Random(SEED)
    titles = list(FAMILIES)
    jobs = [{"id": f"J{i + 1}", "title": t, "location": FAMILIES[t]["location"],
             "description": job_description(t, FAMILIES[t]), "min_experience": FAMILIES[t]["min_exp"],
             "min_education": FAMILIES[t]["edu"], "skills": list(FAMILIES[t]["skills"])}
            for i, t in enumerate(titles)]

    resumes, n = [], 0
    for family in titles:
        for kind, count in (("strong", 10), ("partial", 12)):
            for _ in range(count):
                n += 1
                resumes.append(make_resume(rng, f"R{n:03d}", family, kind))

    # 18 keyword-stuffed resumes: a genuine strong resume from an unrelated family
    # plus a line of keywords copied from the targeted job description.
    for target in titles:
        sources = [f for f in titles if f != target and (f, target) not in RELATED]
        for source in rng.sample(sources, 3):
            n += 1
            r = make_resume(rng, f"R{n:03d}", source, "stuffed")
            r["text"] += "\n\nKeywords: " + ", ".join(FAMILIES[target]["skills"])
            r["target"] = target
            resumes.append(r)

    # Ground-truth labels (Table 3.2)
    for r in resumes:
        r["labels"] = {}
        for job in jobs:
            t = job["title"]
            if r["family"] == t and r["kind"] in ("strong", "stuffed"):
                label = 2
            elif r["family"] == t and r["kind"] == "partial":
                label = 1
            elif (r["family"], t) in RELATED and r["kind"] in ("strong", "stuffed") and r.get("target") != t:
                label = 1
            else:
                label = 0
            r["labels"][job["id"]] = label

    OUT.mkdir(exist_ok=True)
    (OUT / "jobs.json").write_text(json.dumps(jobs, indent=2))
    (OUT / "resumes.json").write_text(json.dumps(resumes, indent=2))
    print(f"Wrote {len(jobs)} jobs and {len(resumes)} resumes to {OUT}")


if __name__ == "__main__":
    main()
'''

# ---------------------------------------------------------------------
# FILE: requirements.txt
# ---------------------------------------------------------------------
FILES['requirements.txt'] = '''Flask>=3.0
Werkzeug>=3.0
scikit-learn>=1.3
pypdf>=4.0
python-docx>=1.1
numpy>=1.26
scipy>=1.11
pytest>=8.0
matplotlib>=3.8  # optional, only for `python -m eval.evaluate --charts`
'''

# ---------------------------------------------------------------------
# FILE: screening/__init__.py
# ---------------------------------------------------------------------
FILES['screening/__init__.py'] = '''from .matcher import DEFAULT_WEIGHTS, SHORTLIST_THRESHOLD, rank_candidates
from .parser import EDUCATION_NAMES, extract_text, parse_resume

__all__ = ["DEFAULT_WEIGHTS", "SHORTLIST_THRESHOLD", "rank_candidates",
           "EDUCATION_NAMES", "extract_text", "parse_resume"]
'''

# ---------------------------------------------------------------------
# FILE: screening/matcher.py
# ---------------------------------------------------------------------
FILES['screening/matcher.py'] = '''"""Hybrid screening model (Sections 3.7.4 - 3.7.6) and the baseline methods (Section 3.8)."""

import re
from dataclasses import dataclass, field

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from .parser import parse_job, parse_resume
from .skills import SKILL_TAXONOMY

DEFAULT_WEIGHTS = {"text": 0.35, "skills": 0.40, "experience": 0.15, "education": 0.10}
SHORTLIST_THRESHOLD = 60  # best balance of precision and recall (Table 4.6)


@dataclass
class MatchResult:
    candidate_id: str
    score: float            # 0 - 100
    text_score: float       # 0 - 1 for each component
    skill_score: float
    experience_score: float
    education_score: float
    matched_skills: list = field(default_factory=list)
    missing_skills: list = field(default_factory=list)

    def breakdown(self):
        return {
            "text": self.text_score,
            "skills": self.skill_score,
            "experience": self.experience_score,
            "education": self.education_score,
            "matched": self.matched_skills,
            "missing": self.missing_skills,
        }


def experience_fit(years, required):
    """Candidate years / required years, capped at 1."""
    if not required:
        return 1.0
    return min(years / required, 1.0)


def education_fit(level, required):
    """1 if the candidate meets the required level, proportionally lower otherwise."""
    if not required:
        return 1.0
    return min(level / required, 1.0)


def rank_candidates(job_description, resumes, weights=None, **job_kwargs):
    """resumes: dict {candidate_id: resume_text}. Returns results sorted by score."""
    weights = weights or DEFAULT_WEIGHTS   # text 0.35, skills 0.40, exp 0.15, edu 0.10
    job = parse_job(job_description, **job_kwargs)
    parsed = {cid: parse_resume(txt) for cid, txt in resumes.items()}
    if not parsed:
        return []

    ids = list(parsed)
    corpus = [job["clean_text"]] + [parsed[c]["clean_text"] for c in ids]
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1, 2), sublinear_tf=True)
    matrix = vec.fit_transform(corpus)
    sims = cosine_similarity(matrix[0:1], matrix[1:]).ravel()

    results = []
    for i, cid in enumerate(ids):
        p = parsed[cid]
        cand_skills = set(p["skills"])
        matched = sorted(job["skills"] & cand_skills)
        missing = sorted(job["skills"] - cand_skills)
        skill_score = len(matched) / len(job["skills"]) if job["skills"] else 0.0
        exp_score = experience_fit(p["experience_years"], job["min_experience"])
        edu_score = education_fit(p["education_level"], job["min_education"])
        text_score = min(sims[i] / 0.5, 1.0)
        total = (weights["text"] * text_score + weights["skills"] * skill_score
                 + weights["experience"] * exp_score + weights["education"] * edu_score)
        results.append(MatchResult(cid, round(total * 100, 2), round(float(text_score), 4),
                                   round(skill_score, 4), round(exp_score, 4),
                                   round(edu_score, 4), matched, missing))
    return sorted(results, key=lambda r: r.score, reverse=True)


# ---------------------------------------------------------------------------
# Baseline methods used for comparison in Chapter IV
# ---------------------------------------------------------------------------

def keyword_scores(job_skills, resumes):
    """Method A - Boolean keyword: share of the job's skill words found exactly as written."""
    scores = {}
    for cid, text in resumes.items():
        low = f" {text.lower()} "
        hits = sum(1 for s in job_skills
                   if re.search(rf"(?<![a-z0-9]){re.escape(s.lower())}(?![a-z0-9])", low))
        scores[cid] = 100 * hits / len(job_skills) if job_skills else 0.0
    return scores


def tfidf_scores(job_description, resumes):
    """Method B - TF-IDF only: cosine similarity between the job and each resume."""
    from .parser import normalise
    ids = list(resumes)
    corpus = [normalise(job_description)] + [normalise(resumes[c]) for c in ids]
    vec = TfidfVectorizer(stop_words="english", ngram_range=(1, 2), sublinear_tf=True)
    matrix = vec.fit_transform(corpus)
    sims = cosine_similarity(matrix[0:1], matrix[1:]).ravel()
    return {cid: 100 * float(s) for cid, s in zip(ids, sims)}


def skill_scores(job_skills, resumes):
    """Method C - skill match only, using the synonym taxonomy."""
    from .parser import extract_skills
    job_skills = set(job_skills)
    return {cid: 100 * len(job_skills & extract_skills(t)) / len(job_skills) if job_skills else 0.0
            for cid, t in resumes.items()}


def known_skills():
    return sorted(SKILL_TAXONOMY)
'''

# ---------------------------------------------------------------------
# FILE: screening/parser.py
# ---------------------------------------------------------------------
FILES['screening/parser.py'] = r'''"""Resume text extraction and field extraction (Sections 3.7.1 and 3.7.2 of the report)."""

import re
from pathlib import Path

from .skills import SYNONYM_TO_SKILL

EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
# Indian mobile number: optional +91 / 91 / 0 prefix, then 10 digits starting 6-9
PHONE_RE = re.compile(r"(?:\+?91[\s-]?|0)?([6-9]\d{4}[\s-]?\d{5})\b")
YEARS_RE = re.compile(r"(\d+(?:\.\d+)?)\s*\+?\s*(?:years?|yrs?)\b", re.IGNORECASE)

# Highest level wins: diploma 1, bachelor 2, master/MBA 3, doctorate 4.
EDUCATION_LEVELS = [
    (4, r"ph\.?\s?d|doctorate|doctor of philosophy"),
    (3, r"m\.?\s?tech|m\.e\.|m\.?\s?sc|m\.?\s?com|mca|mba|pgdm|master'?s?|post[- ]graduate"),
    (2, r"b\.?\s?tech|b\.e\.|b\.?\s?sc|b\.?\s?com|bca|bba|b\.a\.|bachelor'?s?|graduate|degree"),
    (1, r"diploma|polytechnic|12th|hsc"),
]
EDUCATION_NAMES = {0: "Not specified", 1: "Diploma", 2: "Bachelor's", 3: "Master's / MBA", 4: "Doctorate"}


def extract_text(path):
    """Read plain text from a PDF, DOCX or TXT resume."""
    path = Path(path)
    ext = path.suffix.lower()
    if ext == ".pdf":
        from pypdf import PdfReader
        reader = PdfReader(str(path))
        return "\n".join(page.extract_text() or "" for page in reader.pages)
    if ext == ".docx":
        import docx
        document = docx.Document(str(path))
        parts = [p.text for p in document.paragraphs]
        for table in document.tables:
            for row in table.rows:
                parts.extend(cell.text for cell in row.cells)
        return "\n".join(parts)
    if ext == ".txt":
        return path.read_text(encoding="utf-8", errors="ignore")
    raise ValueError(f"Unsupported file type: {ext}")


def normalise(text):
    """Lower-case, strip special characters and collapse repeated spaces."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9+#/.\-\s]", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def extract_skills(text):
    """Map every known synonym found in the text to its canonical skill."""
    clean = f" {normalise(text)} "
    found = set()
    for syn, canon in SYNONYM_TO_SKILL.items():
        if re.search(rf"(?<![a-z0-9]){re.escape(syn)}(?![a-z0-9])", clean):
            found.add(canon)
    return found


def extract_experience(text):
    """Largest "N years" figure in the text, taken as years of experience."""
    values = [float(v) for v in YEARS_RE.findall(text)]
    values = [v for v in values if v <= 45]  # ignore obvious noise such as "100 years"
    return max(values) if values else 0.0


def extract_education(text):
    """Highest education level on the 0-4 scale."""
    low = text.lower()
    for level, pattern in EDUCATION_LEVELS:
        if re.search(rf"\b(?:{pattern})", low):
            return level
    return 0


def extract_email(text):
    match = EMAIL_RE.search(text)
    return match.group(0) if match else None


def extract_phone(text):
    match = PHONE_RE.search(text)
    return re.sub(r"[\s-]", "", match.group(1)) if match else None


def parse_resume(text):
    return {
        "clean_text": normalise(text),
        "email": extract_email(text),
        "phone": extract_phone(text),
        "experience_years": extract_experience(text),
        "education_level": extract_education(text),
        "skills": extract_skills(text),
    }


def parse_job(description, min_experience=None, min_education=None, skills=None):
    """Parse a job description. Explicit values override what is read from the text."""
    return {
        "clean_text": normalise(description),
        "skills": set(skills) if skills else extract_skills(description),
        "min_experience": float(min_experience) if min_experience is not None
        else extract_experience(description),
        "min_education": int(min_education) if min_education is not None
        else extract_education(description),
    }
'''

# ---------------------------------------------------------------------
# FILE: screening/skills.py
# ---------------------------------------------------------------------
FILES['screening/skills.py'] = '''"""Skill taxonomy: canonical skills mapped to their synonyms and alternative spellings.

Each canonical skill lists the ways it is commonly written in resumes and job
descriptions. The parser searches for every synonym as a whole word and maps it
back to the canonical name (Section 3.7.3 of the report).
"""

SKILL_TAXONOMY = {
    # Programming and backend
    "python": ["python", "python3"],
    "java": ["java", "core java", "j2ee"],
    "javascript": ["javascript", "js", "es6", "ecmascript"],
    "django": ["django", "django rest framework", "drf"],
    "flask": ["flask"],
    "fastapi": ["fastapi", "fast api"],
    "rest api": ["rest api", "rest apis", "restful", "restful api", "restful services"],
    "sql": ["sql", "mysql", "postgresql", "postgres", "t-sql", "tsql", "pl/sql", "sqlite", "ms sql"],
    "nosql": ["nosql", "mongodb", "mongo", "cassandra", "dynamodb"],
    "git": ["git", "github", "gitlab", "bitbucket", "version control"],
    "oop": ["oop", "object oriented programming", "object-oriented programming"],
    # Cloud and DevOps
    "aws": ["aws", "amazon web services", "ec2", "s3", "lambda"],
    "azure": ["azure", "microsoft azure"],
    "gcp": ["gcp", "google cloud", "google cloud platform"],
    "docker": ["docker", "containerization", "containers", "dockerfile"],
    "kubernetes": ["kubernetes", "k8s", "eks", "aks", "gke", "helm"],
    "linux": ["linux", "unix", "ubuntu", "centos", "rhel"],
    "ci/cd": ["ci/cd", "ci cd", "cicd", "continuous integration", "continuous delivery",
              "jenkins", "github actions", "gitlab ci"],
    "terraform": ["terraform", "infrastructure as code", "iac"],
    "ansible": ["ansible"],
    "shell scripting": ["shell scripting", "bash", "shell script", "bash scripting"],
    "monitoring": ["monitoring", "prometheus", "grafana", "nagios", "datadog"],
    # Data
    "excel": ["excel", "ms excel", "microsoft excel", "advanced excel", "vlookup", "pivot tables"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "power bi": ["power bi", "powerbi"],
    "tableau": ["tableau"],
    "statistics": ["statistics", "statistical analysis", "hypothesis testing", "regression analysis"],
    "data visualization": ["data visualization", "data visualisation", "dashboards", "dashboard"],
    "machine learning": ["machine learning", "ml", "scikit-learn", "sklearn"],
    # QA
    "selenium": ["selenium", "selenium webdriver", "webdriver"],
    "manual testing": ["manual testing", "functional testing", "regression testing", "test cases"],
    "automation testing": ["automation testing", "test automation", "automated testing"],
    "jira": ["jira", "bug tracking", "defect tracking"],
    "api testing": ["api testing", "postman", "rest assured"],
    "pytest": ["pytest", "unittest", "testng", "junit"],
    "agile": ["agile", "scrum", "sprint", "kanban"],
    # HR
    "recruitment": ["recruitment", "talent acquisition", "recruiting", "sourcing", "end-to-end recruitment"],
    "onboarding": ["onboarding", "induction", "joining formalities"],
    "payroll": ["payroll", "payroll processing", "salary processing"],
    "employee engagement": ["employee engagement", "employee relations", "engagement activities"],
    "hrms": ["hrms", "hris", "workday", "successfactors", "zoho people"],
    "labour law": ["labour law", "labor law", "statutory compliance", "pf", "esic"],
    "performance management": ["performance management", "appraisals", "performance appraisal", "kra", "kpi setting"],
    # Digital marketing
    "seo": ["seo", "search engine optimization", "search engine optimisation"],
    "sem": ["sem", "google ads", "adwords", "ppc", "pay per click"],
    "social media marketing": ["social media marketing", "smm", "social media", "instagram marketing",
                               "facebook ads", "meta ads", "linkedin marketing"],
    "content marketing": ["content marketing", "content writing", "copywriting", "blogging"],
    "google analytics": ["google analytics", "ga4", "web analytics"],
    "email marketing": ["email marketing", "mailchimp", "email campaigns"],
    # General
    "communication": ["communication", "communication skills", "verbal communication", "written communication"],
}

# Reverse index: synonym -> canonical skill. Longer synonyms first so that
# "django rest framework" is preferred over "rest" when reading the output.
SYNONYM_TO_SKILL = {
    syn.lower(): canon
    for canon, syns in SKILL_TAXONOMY.items()
    for syn in sorted(syns, key=len, reverse=True)
}
'''

# ---------------------------------------------------------------------
# FILE: seed_demo.py
# ---------------------------------------------------------------------
FILES['seed_demo.py'] = r'''"""Load demo data: one recruiter, the six job descriptions and 8 job seekers with resumes.

Usage:  python seed_demo.py      (run eval/generate_dataset.py first)
Logins: recruiter hr@demo.com / demo123   ·   job seekers c0@demo.com ... c7@demo.com / demo123
"""

import json
import random
from pathlib import Path

from werkzeug.security import generate_password_hash

import app as portal
from screening import parse_resume, rank_candidates

DATA = Path(__file__).resolve().parent / "eval" / "data"


def main():
    if not (DATA / "jobs.json").exists():
        raise SystemExit("Run `python -m eval.generate_dataset` first.")
    jobs = json.loads((DATA / "jobs.json").read_text())
    resumes = json.loads((DATA / "resumes.json").read_text())
    rng = random.Random(7)
    with portal.app.app_context():
        db = portal.db()
        if db.execute("SELECT 1 FROM users WHERE email = 'hr@demo.com'").fetchone():
            raise SystemExit("Demo data already loaded.")
        pw = generate_password_hash("demo123")
        rid = db.execute("INSERT INTO users (name, email, password, role) VALUES (?, ?, ?, 'recruiter')",
                         ("Qollabb Talent Team", "hr@demo.com", pw)).lastrowid
        job_ids = [db.execute("INSERT INTO jobs (recruiter_id, title, location, description, min_experience) "
                              "VALUES (?, ?, ?, ?, ?)",
                              (rid, j["title"], j["location"], j["description"], j["min_experience"])).lastrowid
                   for j in jobs]
        # 8 seekers apply to the first job (Python Backend Developer): a mix of strong, partial and other
        py = [r for r in resumes if r["family"] == jobs[0]["title"]]
        pool = [r for r in py if r["kind"] == "strong"][:3] + [r for r in py if r["kind"] == "partial"][:3] \
            + rng.sample([r for r in resumes if r["family"] != jobs[0]["title"]], 2)
        uploads = Path(portal.app.config["UPLOAD_FOLDER"])
        uploads.mkdir(exist_ok=True)
        for i, r in enumerate(pool):
            name = r["text"].split("\n")[0]
            sid = db.execute("INSERT INTO users (name, email, password, role) VALUES (?, ?, ?, 'seeker')",
                             (name, f"c{i}@demo.com", pw)).lastrowid
            fname = f"{sid}_{job_ids[0]}.txt"
            (uploads / fname).write_text(r["text"])
            res = rank_candidates(jobs[0]["description"], {"self": r["text"]},
                                  min_experience=jobs[0]["min_experience"])[0]
            p = parse_resume(r["text"])
            b = res.breakdown()
            b.update(experience_years=p["experience_years"], education_level=p["education_level"],
                     phone=p["phone"], parsed_email=p["email"])
            db.execute("INSERT INTO applications (job_id, seeker_id, resume_path, score, breakdown) "
                       "VALUES (?, ?, ?, ?, ?)", (job_ids[0], sid, fname, res.score, json.dumps(b)))
        db.commit()
    print("Demo data loaded. Recruiter: hr@demo.com / demo123, seekers: c0..c7@demo.com / demo123")


if __name__ == "__main__":
    main()
'''

# ---------------------------------------------------------------------
# FILE: static/style.css
# ---------------------------------------------------------------------
FILES['static/style.css'] = ''':root { --fg:#1f2937; --muted:#6b7280; --line:#e5e7eb; --accent:#2b5c9b; --bg:#fff; --soft:#f8fafc; }
* { box-sizing:border-box; }
body { margin:0; font-family:system-ui,-apple-system,"Segoe UI",Roboto,sans-serif; color:var(--fg); background:var(--bg); }
.nav { display:flex; justify-content:space-between; align-items:center; padding:14px 24px; border-bottom:1px solid var(--line); }
.brand { font-weight:700; color:var(--fg); text-decoration:none; }
.nav nav a { margin-left:16px; color:var(--accent); }
main { max-width:1100px; margin:0 auto; padding:20px 16px 48px; }
a { color:var(--accent); }
.flash { background:#eef4fb; border:1px solid #c9dbf0; padding:10px 14px; border-radius:6px; margin-bottom:14px; }
.search { display:flex; gap:8px; margin-bottom:18px; }
.search input { flex:1; }
input, select, textarea { padding:8px 10px; border:1px solid #cbd5e1; border-radius:6px; font:inherit; width:100%; }
button, .btn { background:var(--accent); color:#fff; border:0; padding:9px 16px; border-radius:6px; font:inherit; cursor:pointer; text-decoration:none; display:inline-block; }
.search button { width:auto; }
.form { display:grid; gap:14px; max-width:560px; }
.form label { display:grid; gap:6px; font-weight:500; }
.form button { justify-self:start; }
.card { display:block; border:1px solid var(--line); border-radius:8px; padding:14px 18px; margin-bottom:12px; color:inherit; text-decoration:none; background:var(--soft); }
.card:hover { border-color:var(--accent); }
.card h3 { margin:0 0 4px; }
.muted { color:var(--muted); }
.small { font-size:13px; }
.pre { white-space:pre-wrap; }
table { width:100%; border-collapse:collapse; }
th, td { text-align:left; padding:10px 8px; border-bottom:1px solid var(--line); vertical-align:top; }
th { font-size:13px; color:var(--muted); font-weight:600; }
td select { width:auto; }
tr.above td:nth-child(3) strong { color:#15803d; }
.missing { color:#b45309; }
.status { padding:2px 8px; border-radius:10px; background:#eef2f7; font-size:13px; }
.s-shortlisted, .s-interview, .s-hired { background:#dcfce7; }
.s-rejected { background:#fee2e2; }
@media (max-width:700px) { table { display:block; overflow-x:auto; } .nav { flex-direction:column; gap:8px; } }
'''

# ---------------------------------------------------------------------
# FILE: templates/apply.html
# ---------------------------------------------------------------------
FILES['templates/apply.html'] = '''{% extends "base.html" %}
{% block title %}Apply · {{ job.title }}{% endblock %}
{% block content %}
<h2>Apply — {{ job.title }}</h2>
<p class="pre">{{ job.description }}</p>
<form class="form" method="post" enctype="multipart/form-data">
  <label>Resume (PDF, DOCX or TXT, max 5 MB)
    <input type="file" name="resume" accept=".pdf,.docx,.txt" required>
  </label>
  <button>Submit application</button>
</form>
{% endblock %}
'''

# ---------------------------------------------------------------------
# FILE: templates/base.html
# ---------------------------------------------------------------------
FILES['templates/base.html'] = '''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}AI Job Portal{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
<header class="nav">
  <a class="brand" href="{{ url_for('index') }}">AI Job Portal</a>
  <nav>
    <a href="{{ url_for('index') }}">Jobs</a>
    {% if current_role %}
      <a href="{{ url_for('dashboard') }}">Dashboard</a>
      {% if current_role == 'recruiter' %}<a href="{{ url_for('new_job') }}">Post job</a>{% endif %}
      <a href="{{ url_for('logout') }}">Logout</a>
    {% else %}
      <a href="{{ url_for('login') }}">Login</a>
      <a href="{{ url_for('register') }}">Register</a>
    {% endif %}
  </nav>
</header>
<main>
  {% with messages = get_flashed_messages() %}
    {% for m in messages %}<div class="flash">{{ m }}</div>{% endfor %}
  {% endwith %}
  {% block content %}{% endblock %}
</main>
</body>
</html>
'''

# ---------------------------------------------------------------------
# FILE: templates/candidates.html
# ---------------------------------------------------------------------
FILES['templates/candidates.html'] = '''{% extends "base.html" %}
{% block title %}Candidates · {{ job.title }}{% endblock %}
{% block content %}
<h2>Ranked candidates — {{ job.title }}</h2>
<p class="muted">
  Sorted by AI match score (35% text similarity, 40% skills, 15% experience, 10% education).
  {% if only_shortlist %}
    Showing scores ≥ {{ threshold }}. <a href="{{ url_for('candidates', job_id=job.id) }}">Show all</a>
  {% else %}
    <a href="{{ url_for('candidates', job_id=job.id, filter='shortlist') }}">Show only scores ≥ {{ threshold }}</a>
  {% endif %}
</p>
<table>
  <tr><th>#</th><th>Candidate</th><th>Score</th><th>Breakdown</th><th>Matched skills</th><th>Missing skills</th><th>Status</th></tr>
  {% for r in rows %}
  {% set b = r.breakdown|fromjson %}
  <tr class="{% if r.score >= threshold %}above{% endif %}">
    <td>{{ loop.index }}</td>
    <td>{{ r.name }}<br><span class="muted">{{ r.email }}</span><br>
        <a href="{{ url_for('view_resume', app_id=r.id) }}">Resume</a></td>
    <td><strong>{{ r.score|round|int }}</strong></td>
    <td class="small">
      Text {{ (b.text * 100)|round|int }}% · Skills {{ (b.skills * 100)|round|int }}%<br>
      Exp {{ b.experience_years }} yrs ({{ (b.experience * 100)|round|int }}%) ·
      {{ education_names[b.education_level] }}
    </td>
    <td>{{ b.matched|join(', ') }}</td>
    <td class="missing">{{ b.missing|join(', ') }}</td>
    <td>
      <form method="post" action="{{ url_for('update_status', app_id=r.id) }}">
        <select name="status" onchange="this.form.submit()">
          {% for s in statuses %}<option {% if s == r.status %}selected{% endif %}>{{ s }}</option>{% endfor %}
        </select>
        <noscript><button>Save</button></noscript>
      </form>
    </td>
  </tr>
  {% else %}
  <tr><td colspan="7" class="muted">No applications yet.</td></tr>
  {% endfor %}
</table>
<p class="muted small">The AI score is a first-level filter. Final hiring decisions should always be made by a human recruiter.</p>
{% endblock %}
'''

# ---------------------------------------------------------------------
# FILE: templates/index.html
# ---------------------------------------------------------------------
FILES['templates/index.html'] = '''{% extends "base.html" %}
{% block content %}
<form class="search" method="get">
  <input name="q" value="{{ q }}" placeholder="Search jobs by title, skill or location">
  <button>Search</button>
</form>
{% for job in jobs %}
  <a class="card" href="{{ url_for('job_detail', job_id=job.id) }}">
    <h3>{{ job.title }}</h3>
    <p class="muted">{{ job.company }} · {{ job.location or 'Not specified' }} · Min {{ job.min_experience }} yrs</p>
    <p>{{ job.description[:220] }}{% if job.description|length > 220 %}…{% endif %}</p>
  </a>
{% else %}
  <p class="muted">No jobs found.</p>
{% endfor %}
{% endblock %}
'''

# ---------------------------------------------------------------------
# FILE: templates/job_detail.html
# ---------------------------------------------------------------------
FILES['templates/job_detail.html'] = '''{% extends "base.html" %}
{% block title %}{{ job.title }} · AI Job Portal{% endblock %}
{% block content %}
<h2>{{ job.title }}</h2>
<p class="muted">{{ job.company }} · {{ job.location or 'Not specified' }} · Min {{ job.min_experience }} yrs</p>
<p class="pre">{{ job.description }}</p>
{% if current_role == 'seeker' %}
  {% if applied %}
    <p>You applied — match score <strong>{{ applied.score|round|int }}</strong>, status <strong>{{ applied.status }}</strong>.
       <a href="{{ url_for('apply', job_id=job.id) }}">Re-apply with a new resume</a></p>
  {% else %}
    <a class="btn" href="{{ url_for('apply', job_id=job.id) }}">Apply now</a>
  {% endif %}
{% elif not current_role %}
  <a class="btn" href="{{ url_for('login', next=url_for('apply', job_id=job.id)) }}">Log in to apply</a>
{% endif %}
{% endblock %}
'''

# ---------------------------------------------------------------------
# FILE: templates/job_form.html
# ---------------------------------------------------------------------
FILES['templates/job_form.html'] = '''{% extends "base.html" %}
{% block title %}Post a job · AI Job Portal{% endblock %}
{% block content %}
<h2>Post a job</h2>
<form class="form" method="post">
  <label>Job title <input name="title" value="{{ request.form.title }}" required></label>
  <label>Location <input name="location" value="{{ request.form.location }}" placeholder="e.g. Pune (Hybrid)"></label>
  <label>Minimum experience (years) <input name="min_experience" type="number" step="0.5" min="0" value="{{ request.form.min_experience or 0 }}"></label>
  <label>Job description
    <textarea name="description" rows="10" required placeholder="Describe the role. Mention required skills (e.g. python, django, sql, docker) and qualification (e.g. B.Tech or equivalent).">{{ request.form.description }}</textarea>
  </label>
  <p class="muted">Required skills and qualification are read automatically from the description by the AI screening engine.</p>
  <button>Post job</button>
</form>
{% endblock %}
'''

# ---------------------------------------------------------------------
# FILE: templates/login.html
# ---------------------------------------------------------------------
FILES['templates/login.html'] = '''{% extends "base.html" %}
{% block title %}Login · AI Job Portal{% endblock %}
{% block content %}
<h2>Log in</h2>
<form class="form" method="post">
  <label>Email <input name="email" type="email" required></label>
  <label>Password <input name="password" type="password" required></label>
  <button>Log in</button>
</form>
<p class="muted">No account? <a href="{{ url_for('register') }}">Register</a></p>
{% endblock %}
'''

# ---------------------------------------------------------------------
# FILE: templates/recruiter_dashboard.html
# ---------------------------------------------------------------------
FILES['templates/recruiter_dashboard.html'] = '''{% extends "base.html" %}
{% block title %}Recruiter dashboard · AI Job Portal{% endblock %}
{% block content %}
<h2>My job postings</h2>
<p><a class="btn" href="{{ url_for('new_job') }}">Post a new job</a></p>
<table>
  <tr><th>Job</th><th>Location</th><th>Applicants</th><th>Score ≥ {{ threshold }}</th><th></th></tr>
  {% for j in jobs %}
  <tr>
    <td><a href="{{ url_for('job_detail', job_id=j.id) }}">{{ j.title }}</a></td>
    <td>{{ j.location }}</td>
    <td>{{ j.applicants }}</td>
    <td>{{ j.above_threshold or 0 }}</td>
    <td><a href="{{ url_for('candidates', job_id=j.id) }}">Ranked candidates</a></td>
  </tr>
  {% else %}
  <tr><td colspan="5" class="muted">You have not posted any jobs yet.</td></tr>
  {% endfor %}
</table>
{% endblock %}
'''

# ---------------------------------------------------------------------
# FILE: templates/register.html
# ---------------------------------------------------------------------
FILES['templates/register.html'] = '''{% extends "base.html" %}
{% block title %}Register · AI Job Portal{% endblock %}
{% block content %}
<h2>Create an account</h2>
<form class="form" method="post">
  <label>Full name <input name="name" required></label>
  <label>Email <input name="email" type="email" required></label>
  <label>Password <input name="password" type="password" minlength="6" required></label>
  <label>I am a
    <select name="role">
      <option value="seeker">Job seeker</option>
      <option value="recruiter">Recruiter</option>
    </select>
  </label>
  <button>Register</button>
</form>
{% endblock %}
'''

# ---------------------------------------------------------------------
# FILE: templates/seeker_dashboard.html
# ---------------------------------------------------------------------
FILES['templates/seeker_dashboard.html'] = '''{% extends "base.html" %}
{% block title %}My applications · AI Job Portal{% endblock %}
{% block content %}
<h2>My applications</h2>
<table>
  <tr><th>Job</th><th>Match score</th><th>Missing skills</th><th>Status</th><th>Applied</th></tr>
  {% for a in apps %}
  {% set b = a.breakdown|fromjson %}
  <tr>
    <td><a href="{{ url_for('job_detail', job_id=a.job_id) }}">{{ a.title }}</a></td>
    <td><strong>{{ a.score|round|int }}</strong></td>
    <td>{{ b.missing|join(', ') or '—' }}</td>
    <td><span class="status s-{{ a.status|lower }}">{{ a.status }}</span></td>
    <td>{{ a.created_at }}</td>
  </tr>
  {% else %}
  <tr><td colspan="5" class="muted">No applications yet. <a href="{{ url_for('index') }}">Browse jobs</a></td></tr>
  {% endfor %}
</table>
{% endblock %}
'''

# ---------------------------------------------------------------------
# FILE: tests/__init__.py
# ---------------------------------------------------------------------
FILES['tests/__init__.py'] = ''''''

# ---------------------------------------------------------------------
# FILE: tests/conftest.py
# ---------------------------------------------------------------------
FILES['tests/conftest.py'] = '''import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


@pytest.fixture
def client(tmp_path, monkeypatch):
    import app as portal
    portal.app.config.update(TESTING=True, DATABASE=str(tmp_path / "test.db"),
                             UPLOAD_FOLDER=str(tmp_path / "uploads"))
    portal.init_db()
    with portal.app.test_client() as c:
        yield c
'''

# ---------------------------------------------------------------------
# FILE: tests/test_portal.py
# ---------------------------------------------------------------------
FILES['tests/test_portal.py'] = r'''"""Functional test cases from Table 4.1 of the report."""

import io
import sqlite3

import docx

import app as portal

PY_JOB = ("We are hiring a Python Backend Developer. Minimum 2 years of experience. Required skills: "
          "python, django, flask, rest api, sql, git, docker, aws. Qualification: B.Tech or equivalent.")
DA_JOB = ("We are hiring a Data Analyst. Minimum 1 years of experience. Required skills: sql, excel, "
          "python, pandas, power bi, statistics, data visualization, tableau. Qualification: B.Sc or equivalent.")
STRONG = ("Sneha Patil\nsneha@example.com | +91 98765 43210\nPython developer with 4 years of experience.\n"
          "Skills: Python3, Django REST Framework, Flask, RESTful services, PostgreSQL, GitHub, Docker, AWS\n"
          "Education: B.Tech in Computer Science")
WEAK = "Rohan Sharma\nrohan@example.com\nSales executive with 1 year of experience.\nSkills: MS Excel\nEducation: Diploma"


def register(c, name, email, role, password="secret123"):
    return c.post("/register", data=dict(name=name, email=email, password=password, role=role))


def login(c, email, password="secret123"):
    return c.post("/login", data=dict(email=email, password=password))


def post_job(c, title, desc, min_exp):
    return c.post("/jobs/new", data=dict(title=title, location="Pune", description=desc, min_experience=min_exp))


def apply(c, job_id, content, name="resume.txt"):
    return c.post(f"/jobs/{job_id}/apply", data={"resume": (io.BytesIO(content), name)},
                  content_type="multipart/form-data")


def setup_recruiter(c):
    register(c, "Recruiter", "hr@acme.com", "recruiter")
    login(c, "hr@acme.com")
    post_job(c, "Python Backend Developer", PY_JOB, 2)
    post_job(c, "Data Analyst", DA_JOB, 1)
    c.get("/logout")


def test_1_register_hashes_password(client):
    assert register(client, "R", "r@x.com", "recruiter").status_code == 302
    assert register(client, "S", "s@x.com", "seeker").status_code == 302
    conn = sqlite3.connect(portal.app.config["DATABASE"])
    pw = conn.execute("SELECT password FROM users WHERE email='r@x.com'").fetchone()[0]
    assert pw != "secret123" and pw.startswith(("scrypt:", "pbkdf2:"))


def test_2_duplicate_email_refused(client):
    register(client, "R", "r@x.com", "recruiter")
    resp = register(client, "R2", "r@x.com", "seeker")
    assert b"Email already registered" in resp.data


def test_3_wrong_password(client):
    register(client, "R", "r@x.com", "recruiter")
    resp = login(client, "r@x.com", "wrong-password")
    assert resp.status_code == 401 and b"Invalid credentials" in resp.data


def test_4_jobs_on_home_and_dashboard(client):
    setup_recruiter(client)
    home = client.get("/").data
    assert b"Python Backend Developer" in home and b"Data Analyst" in home
    login(client, "hr@acme.com")
    dash = client.get("/dashboard").data
    assert b"Python Backend Developer" in dash and b"Data Analyst" in dash


def test_5_search(client):
    setup_recruiter(client)
    page = client.get("/?q=Analyst").data
    assert b"Data Analyst" in page and b"Python Backend Developer" not in page


def test_6_txt_applications_scored(client):
    setup_recruiter(client)
    for i in range(8):
        register(client, f"Seeker {i}", f"c{i}@demo.com", "seeker")
        login(client, f"c{i}@demo.com")
        apply(client, 1, (STRONG if i % 2 else WEAK).encode())
        client.get("/logout")
    conn = sqlite3.connect(portal.app.config["DATABASE"])
    scores = [r[0] for r in conn.execute("SELECT score FROM applications")]
    assert len(scores) == 8 and all(s is not None for s in scores)


def test_7_docx_resume(client):
    setup_recruiter(client)
    register(client, "S", "s@x.com", "seeker")
    login(client, "s@x.com")
    d = docx.Document()
    for line in STRONG.split("\n"):
        d.add_paragraph(line)
    buf = io.BytesIO()
    d.save(buf)
    resp = apply(client, 1, buf.getvalue(), "resume.docx")
    assert resp.status_code == 302
    page = client.get("/dashboard", follow_redirects=True).data
    assert b"match score" in page.lower()


def test_8_exe_refused(client):
    setup_recruiter(client)
    register(client, "S", "s@x.com", "seeker")
    login(client, "s@x.com")
    resp = apply(client, 1, b"MZ...", "virus.exe")
    page = client.get(resp.headers["Location"]).data
    assert b"Upload a PDF, DOCX or TXT resume." in page


def test_9_seeker_cannot_view_candidates(client):
    setup_recruiter(client)
    register(client, "S", "s@x.com", "seeker")
    login(client, "s@x.com")
    resp = client.get("/jobs/1/candidates")
    assert resp.status_code == 302 and "/login" in resp.headers["Location"]


def test_10_candidates_ranked_with_skills(client):
    setup_recruiter(client)
    for i, text in enumerate([WEAK, STRONG]):
        register(client, f"S{i}", f"s{i}@x.com", "seeker")
        login(client, f"s{i}@x.com")
        apply(client, 1, text.encode())
        client.get("/logout")
    login(client, "hr@acme.com")
    page = client.get("/jobs/1/candidates").data.decode()
    assert page.index("S1") < page.index("S0")   # strong candidate ranked first
    assert "django" in page and "Missing skills" in page


def test_11_status_change_visible_to_seeker(client):
    setup_recruiter(client)
    register(client, "S", "s@x.com", "seeker")
    login(client, "s@x.com")
    apply(client, 1, STRONG.encode())
    client.get("/logout")
    login(client, "hr@acme.com")
    client.post("/applications/1/status", data={"status": "Shortlisted"})
    client.get("/logout")
    login(client, "s@x.com")
    assert b"Shortlisted" in client.get("/dashboard").data


def test_recruiter_cannot_see_other_recruiters_candidates(client):
    setup_recruiter(client)
    register(client, "Other", "other@x.com", "recruiter")
    login(client, "other@x.com")
    assert client.get("/jobs/1/candidates").status_code == 403
'''

# ---------------------------------------------------------------------
# FILE: tests/test_screening.py
# ---------------------------------------------------------------------
FILES['tests/test_screening.py'] = '''from screening.matcher import rank_candidates
from screening.parser import extract_education, extract_experience, extract_skills, parse_resume


def test_synonyms_map_to_canonical_skills():
    skills = extract_skills("Worked with k8s, PostgreSQL and Talent Acquisition")
    assert {"kubernetes", "sql", "recruitment"} <= skills


def test_whole_word_matching():
    assert "java" not in extract_skills("javascript developer")
    assert "javascript" in extract_skills("javascript developer")


def test_experience_and_education():
    assert extract_experience("3 years at X, total 5.5 years of experience") == 5.5
    assert extract_education("MBA in HR, B.Com") == 3
    assert extract_education("Diploma in Mechanical") == 1
    assert extract_education("Please contact me") == 0


def test_contact_fields():
    p = parse_resume("a.b@mail.com  +91 98765 43210")
    assert p["email"] == "a.b@mail.com" and p["phone"] == "9876543210"


def test_hybrid_score_ranks_and_explains():
    jd = "Required skills: python, django, sql, docker. Minimum 2 years of experience. B.Tech."
    res = rank_candidates(jd, {
        "good": "Python, Django, MySQL, Docker. 4 years of experience. B.Tech",
        "bad": "Sales and marketing. 1 year of experience. Diploma",
    })
    assert res[0].candidate_id == "good" and res[0].score > res[1].score
    assert res[0].missing_skills == [] and 0 <= res[1].score <= 100
    assert set(res[1].missing_skills) == {"python", "django", "sql", "docker"}
'''


# =====================================================================
#  CREATE THE FILES, INSTALL LIBRARIES, RUN TESTS AND EVALUATION
# =====================================================================

def run(cmd):
    print("\n$ " + " ".join(cmd))
    return subprocess.run(cmd, cwd=PROJECT).returncode

for path, content in FILES.items():
    full = os.path.join(PROJECT, path)
    os.makedirs(os.path.dirname(full) or ".", exist_ok=True)
    with open(full, "w", encoding="utf-8") as fh:
        fh.write(content)
os.makedirs(os.path.join(PROJECT, "uploads"), exist_ok=True)
print(f"Created {len(FILES)} files in ./{PROJECT}")

run([sys.executable, "-m", "pip", "install", "-q", "-r", "requirements.txt"])
code = run([sys.executable, "-m", "pytest", "-v"])
print("\nALL TESTS PASSED" if code == 0 else "\nSOME TESTS FAILED - see output above")

run([sys.executable, "-m", "eval.generate_dataset"])
run([sys.executable, "-m", "eval.evaluate"])

print("""
To open the website:
  - On your computer:  cd job_portal  then  python seed_demo.py  and  python app.py
                       and open http://127.0.0.1:5000
  - In Colab, run this in a NEW cell:
        import subprocess, time, os
        os.chdir('job_portal'); subprocess.run(['python', 'seed_demo.py'])
        server = subprocess.Popen(['python', 'app.py']); time.sleep(3)
        from google.colab import output; output.serve_kernel_port_as_window(5000, path='/')
Logins: recruiter hr@demo.com / demo123   job seeker c0@demo.com / demo123
""")
